### ISSUE TITLE
ERROR: LoadError: StringIndexError

### ISSUE THREAD

**Issue by rowlesmr** [jamesrhester/julia_cif_tools#8]
From https://github.com/COMCIFS/cif_core/issues/414 and links therein

There is an error:
```
ERROR: LoadError: StringIndexError: invalid index [21], valid nearby indices [20]=>'°', [22]=>'''
```
(plus some more information after that)

In the file in question, the characters '°' and ''' are adjacent, and so should be at indicies 20 and 21; the 22 is right out.

**Comment by jamesrhester** [comment]
Fixed in 6be8d69. Character strings in Julia give errors if there is an attempt to access the string at a point where a character does not start. When stripping off delimiters, the index of the new final character will not be one less than the index of a single-character delimiter if that final character is a non-ASCII character. Code changed throughout to use the proper Julia idiom for jumping forward/back by one character.
